project_name: nanoproxy
dist: dist
before:
  hooks:
    - go mod tidy

builds:
  - binary: nanoproxy
    ldflags:
      - -s -w -X github.com/ryanbekhen/nanoproxy.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

dockers:
  - image_templates:
      - "ghcr.io/ryanbekhen/nanoproxy:{{ .Version }}"
      - "ghcr.io/ryanbekhen/nanoproxy:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/ryanbekhen/nanoproxy
      - --label=org.opencontainers.image.source=https://github.com/ryanbekhen/nanoproxy
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/ryanbekhen/nanoproxy
    description: "nanoproxy is a simple reverse proxy written in Go."
    maintainer: "Achmad Irianto Eka Putra <i@ryanbekhen.dev>"
    license: "MIT"
    vendor: ryanbekhen
    contents:
      - src: systemd/nanoproxy.service
        dst: /etc/systemd/system/nanoproxy.service
        type: "config|noreplace"
      - src: config/nanoproxy
        dst: /etc/nanoproxy/nanoproxy
        type: "config|noreplace"
    formats:
      - apk
      - deb
      - rpm

brews:
  - name: nanoproxy
    homepage: https://github.com/ryanbekhen/nanoproxy
    description: "nanoproxy is a simple reverse proxy written in Go."
    license: "MIT"
    folder: Formula
    install: |
      bin.install "nanoproxy"
    repository:
      owner: ryanbekhen
      name: nanoproxy
      branch: master

winget:
  - name: nanoproxy
    package_identifier: ryanbekhen.nanoproxy
    publisher: ryanbekhen
    description: "nanoproxy is a simple reverse proxy written in Go."
    short_description: "nanoproxy is a simple reverse proxy written in Go."
    publisher_url: https://ryanbekhen.dev
    publisher_support_url: https://ryanbekhen.dev
    license: MIT
    license_url: https://github.com/ryanbekhen/nanoproxy/blob/master/LICENSE
    homepage: https://github.com/ryanbekhen/nanoproxy
    author: ryanbekhen
    release_notes: "{{.Changelog}}"
    copyright: ryanbekhen
    copyright_url: https://github.com/ryanbekhen/nanoproxy/blob/master/LICENSE
    tags:
      - Proxy
      - Socks5
    repository:
      owner: ryanbekhen
      name: nanoproxy
      branch: master

release:
  draft: false

publishers:
  - name: fury.io
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/ryanbekhen/

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  use: git
  sort: asc
  groups:
    - title: ':rocket: Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: ':bug: Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: ':hammer_and_wrench: Enhancements'
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: ':gear: Others'
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch